### ISSUE TITLE
add trump dumb face image

### ISSUE THREAD

**Issue by heinburger** [tophboogie/trumptweets#10]
should we just have 5 - like that just correspond directly to the emotional states from watson? it would be cool if there was a way to blur them together - like give the actual weights

**Comment by heinburger** [comment]
so, I was thinking about this one @tophboogie  -what do you think about the art on these emojis? http://trumpoji.com/ - I think we could do sometihng similar. I talked with my friend at work and she might be willing to contribute some drawings

**Comment by tophboogie** [comment]
This one:

![angrytrump](https://cloud.githubusercontent.com/assets/5396182/22449022/43f4a81a-e712-11e6-9bbe-914994c29161.jpg)

**Comment by tophboogie** [comment]
closing until we take up tone project
