### ISSUE TITLE
use react-create-app for the frontend

### ISSUE THREAD

**Issue by heinburger** [tophboogie/trumptweets#21]
it handles everything. 🌵

**Comment by heinburger** [comment]
https://github.com/facebookincubator/create-react-app

**Comment by tophboogie** [comment]
seems like a nice bootstrapping tool -- but our project already has these things set up... unless am I missing something?

**Comment by heinburger** [comment]
ok - closing - we might want to move to webpack 2, though because that might bring down the bundle sizes a bit with the treeshaking - I think as of now the js bundle is like 1.5mb or something which is pretty big. must be the d3 stuff?
