### ISSUE TITLE
Move string to array conversion to backend

### ISSUE THREAD

**Issue by tophboogie** [tophboogie/trumptweets#24]
loading new wordclouds is slow, especially for longer time periods. it would be more efficient to have the backend convert tweet string into array of words and store in database. side benefit: being able to query db word arrays, sort alphabetically, and manually remove any weird characters that slip through the regular expression.
also - we could prolly do a better regular expression for removing punctuation...

**Comment by heinburger** [comment]
@tophboogie  - this is a great idea! I had to make some changes to the array stuff because something was failing if something happened (sorry I can't remember) - maybe we can work on this later? I will be up when you get up, maybe - we can do a quick chat about how we want to push this forward?

**Comment by heinburger** [comment]
also this is quite slow on the frontend -like if you select a large date range.. if it was on the backend, our loader would also work and it might get rid of the bug where the wordcloud is redrawn

**Comment by tophboogie** [comment]
fixed by #31
